# Generated by Django 5.2 on 2025-04-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
